---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - PASSWORD=password #optional
      - SUDO_PASSWORD=password #optional
      - PROXY_DOMAIN=code.roadmaps.link #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /home/scott/code-server/data/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
